Mandd/margin solver enh
idaholab/SR2ML pull request #49
Opened 2022-07-21 22:48 UTC by mandd

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Regression tests have to complete successfully.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [ ] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

2022-07-28 20:25 UTC, wangcj05 commented
@mandd test failed: 
![image](https://user-images.githubusercontent.com/7321071/181630817-d6f66164-810b-46a5-b3ae-46d4c6e0f53e.png)

2022-07-28 21:04 UTC, wangcj05 requested changes
I have some minor comments for your consideration.

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +            self.solver['setType'] = setType
I guess you need to add another check outside the for look through xmlNode. Since setType is required, if it does not present in the input, the current code at this stage will not error out. I guess we should start to think to use raven inputspecs in SR2ML.

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +    print(container.__dict__)
do you need this print?

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +      @ In, inputs, inputDict, dictionary containing the probability  value of all basic events
change "inputs" to "inputDict"

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +    epsilon = 0.01
I suggest to move epsilon to the function keyword, and provide default value there, instead of hard coding here.

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +      tempDict[key] = tempDict[key] * (1.-epsilon)
Please add some comment here to explain the perturbation here.

2022-07-28 21:04 UTC, wangcj05 commented on tests/test_MCSSolver_margin_pathsets.xml
> +      <variables>statusA,statusB,statusC,statusD,statusE,
I suggest to use inputs and outputs instead of variables

2022-07-28 21:04 UTC, wangcj05 commented on src/MCSSolver.py
> +  def marginSensitivities(self, MsysBase, inputDict):
For now, this method is ok, I think in the future, we may need to reconsider the method to compute sensitivities.

2023-06-27 17:11 UTC, mandd commented on src/MCSSolver.py
> +  def marginSensitivities(self, MsysBase, inputDict):
Mattia is looking at this portion here

2023-06-27 17:11 UTC, mandd commented on src/MCSSolver.py
> +      @ In, inputs, inputDict, dictionary containing the probability  value of all basic events
fixed

2023-06-27 17:11 UTC, mandd commented on src/MCSSolver.py
> +    epsilon = 0.01
fixed

2023-06-27 17:11 UTC, mandd commented on src/MCSSolver.py
> +      tempDict[key] = tempDict[key] * (1.-epsilon)
added; more edits will be provided from Mattia's analysis

2023-06-27 17:11 UTC, mandd commented on tests/test_MCSSolver_margin_pathsets.xml
> +      <variables>statusA,statusB,statusC,statusD,statusE,
fixed

2023-06-27 17:11 UTC, mandd commented on src/MCSSolver.py
> +            self.solver['setType'] = setType
I agree, input specs would help.
BTW: test has been added

2023-09-22 16:54 UTC, mandd commented
@wangcj05 : I think this PR is good to go

2023-09-22 17:11 UTC, wangcj05 commented
[like]  Congjian Wang reacted to your message:
________________________________
From: Diego Mandelli ***@***.***>
Sent: Friday, September 22, 2023 4:54:25 PM
To: idaholab/SR2ML ***@***.***>
Cc: Congjian Wang ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/SR2ML] Mandd/margin solver enh (PR #49)


@wangcj05<https://github.com/wangcj05> : I think this PR is good to go

—
Reply to this email directly, view it on GitHub<https://github.com/idaholab/SR2ML/pull/49#issuecomment-1731740978>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABX3L35HRED6XPSTGBSZRODX3W7EDANCNFSM54JH54NQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-09-22 17:21 UTC, wangcj05 requested changes
There is one missing doctoring

2023-09-22 17:21 UTC, wangcj05 commented on src/MCSSolver.py
> +def beReader(fileID):
doctoring is missing here

2023-09-22 18:05 UTC, mandd commented on src/MCSSolver.py
> +def beReader(fileID):
added

2023-09-22 18:15 UTC, wangcj05 approved these changes
Changes look good.

2023-09-22 19:36 UTC, wangcj05 commented
PR checklist is satisfied.

2023-09-22 19:36 UTC, merged