Preprocessing text and automatic spell checking
idaholab/SR2ML pull request #61
Opened 2022-10-25 21:16 UTC by dgarrett622

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?
Adds capability to preprocess text using textacy and numerizer. Adds automatic spelling correction. Adds Jupyter notebooks to demonstrate preprocessing capabilities.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Regression tests have to complete successfully.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [ ] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

2022-11-23 22:16 UTC, wangcj05 requested changes
@dgarrett622 I have some general comments for you to consider.

2022-11-23 22:16 UTC, wangcj05 commented on src/nlp/Preprocessing.py
> +textacy_normalize = ['bullet_points',
we are following RAVEN code standards, could you change it to camelBack?

2022-11-23 22:16 UTC, wangcj05 commented on src/nlp/Preprocessing.py
> +textacy_remove = ['accents',
camelBack here?

2022-11-23 22:16 UTC, wangcj05 commented on src/nlp/Preprocessing.py
> +textacy_replace = ['currency_symbols',
camelBack here?

2022-11-23 22:36 UTC, dgarrett622 commented on src/nlp/Preprocessing.py
> +textacy_normalize = ['bullet_points',
changed to textacyNormalize

2022-11-23 22:36 UTC, dgarrett622 commented on src/nlp/Preprocessing.py
> +textacy_remove = ['accents',
changed to textacyRemove

2022-11-23 22:36 UTC, dgarrett622 commented on src/nlp/Preprocessing.py
> +textacy_replace = ['currency_symbols',
changed to textacyReplace

2022-11-23 23:05 UTC, wangcj05 approved these changes

2022-11-28 15:25 UTC, wangcj05 commented
PR is good, and checklist is satisfied.

2022-11-28 15:25 UTC, merged