[WIP] Mandd/mc ssolver td
idaholab/SR2ML pull request #7
Opened 2021-01-19 22:51 UTC by mandd

2021-01-20 04:16 UTC, wangcj05 requested changes
several comments. After you addressed all comments, please make sure the user manual can be compiled and all SR2ML tests are green on your local machine

2021-01-20 04:16 UTC, wangcj05 commented on doc/user_manual/include/MCSsolver.tex
> +      <ExternalModel name="MCSmodel" subType="PRAplugin.MCSSolver">
change PRAplugin.MCSSolver to SR2ML.MCSSolver

2021-01-20 04:16 UTC, wangcj05 commented on doc/user_manual/include/MCSsolver.tex
> +                  True (see test\_MCSSolver_TD_fromPS.xml). As an example, the PointSet contains the IDs of the basic events
test\_MCSSolver_TD_fromPS.xml --> test\_MCSSolver\_TD\_fromPS.xml

2021-01-20 04:16 UTC, wangcj05 commented on doc/user_manual/include/MCSsolver.tex
> +                  (\xmlNode{BE_ID} node) and the initial and final time values (\xmlNode{tInitial} and \xmlNode{tEnd} nodes).
BE_ID --> BE\_ID?

2021-01-20 04:16 UTC, wangcj05 commented on doc/user_manual/include/MCSsolver.tex
> +      <ExternalModel name="MCSmodel" subType="PRAplugin.MCSSolver">
change PRAplugin.MCSSolver to SR2ML.MCSSolver

2021-01-20 04:16 UTC, wangcj05 commented on doc/user_manual/include/MCSsolver.tex
> +  \item test\_MCSSolver_TD_fromPS.xml
test\_MCSSolver_TD.xml --> test\_MCSSolver\_TD.xml
\item test\_MCSSolver\_TD\_fromPS.xml

2021-01-20 04:16 UTC, wangcj05 commented on src/MCSSolver.py
> +    self.TimeDependentMode= True
self.TimeDependentMode --> self.timeDependentMode
Also, please provide inline comments for this variable.

2021-01-20 04:16 UTC, wangcj05 commented on src/MCSSolver.py
> +    self.timeDepData = None
move this to __init__ method

2021-01-20 04:16 UTC, wangcj05 commented on src/MCSSolver.py
> +        self.timeDepData = self.generateHistorySetFromSchedule(container,input.asDataset())
predefine self variable in __init__ method

2021-01-20 04:16 UTC, wangcj05 commented on src/MCSSolver.py
> +  def McsSolver(self, inputDict):
McsSolver --> mcsSolver

2021-01-20 04:16 UTC, wangcj05 commented on tests/MCSSolverTDfromPS/maintenanceSchedule.xml
> +<DataObjectMetadata name="sim_PS">
do you need this file?

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD.xml
> +    <name>PRAplugin/MCSSolverTD</name>
change PRAplugin to SR2ML

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD.xml
> +    <classesTested>PRAplugin/MCSSolver</classesTested>
change PRAplugin to SR2ML

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD.xml
> +    <ExternalModel name="MCSmodel" subType="PRAplugin.MCSSolver">
change PRAplugin to SR2ML

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD_fromPS.xml
> +    <name>PRAplugin/MCSSolverTD_PS</name>
change PRAplugin to SR2ML

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD_fromPS.xml
> +    <classesTested>PRAplugin/MCSSolver</classesTested>
change PRAplugin to SR2ML

2021-01-20 04:16 UTC, wangcj05 commented on tests/test_MCSSolver_TD_fromPS.xml
> +    <ExternalModel name="MCSmodel" subType="PRAplugin.MCSSolver">
change PRAplugin to SR2ML

2021-01-21 22:09 UTC, mandd commented
Comments have been addressed and test have been run on local machine.
Board is green on my MAC (see below)
![Screen Shot 2021-01-21 at 3 07 45 PM](https://user-images.githubusercontent.com/9355268/105418516-7eaab380-5bfa-11eb-8925-4dbb7071c219.png)

2021-01-21 22:22 UTC, wangcj05 approved these changes

2021-01-21 22:23 UTC, wangcj05 commented
Have you tried to build the manual? @mandd

2021-01-21 23:24 UTC, mandd commented
@wangcj05 : good catch, I found an error that I have fixed. Now the user_manual compiles correctly

2021-01-21 23:52 UTC, wangcj05 approved these changes

2021-01-21 23:53 UTC, wangcj05 commented
PR is good to me.

2021-01-21 23:55 UTC, merged