Mandd/abbr improv
idaholab/SR2ML pull request #75
Opened 2023-06-12 21:51 UTC by mandd

--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Regression tests have to complete successfully.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [ ] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

2023-06-13 05:18 UTC, wangcj05 requested changes
@mandd I have some general comments for you to consider, in addition, there are some trailing whitespace issue which caused the failure of pre-test.

2023-06-13 05:18 UTC, wangcj05 commented on src/utils/nlpUtils/OPLparser.py
> +    @out: processList, list, list of function elements contained in the OPL file
Please update the docstring, it seems this function accept no input argument, and return no output.

2023-06-13 05:18 UTC, wangcj05 commented on src/utils/nlpUtils/OPLparser.py
> +    @out: objectList, sentences, list of sentenced contained in the OPL file
update the docstring here, no input and no output for this function

2023-06-13 05:18 UTC, wangcj05 commented on src/utils/nlpUtils/OPLparser.py
> +    @out: objectList: sentences, list of sentenced contained in the OPL file
please update the docstring for this function, no input and no output for this function

2023-06-13 15:38 UTC, mandd commented on src/utils/nlpUtils/OPLparser.py
> +    @out: processList, list, list of function elements contained in the OPL file
fixed

2023-06-13 15:40 UTC, mandd commented on src/utils/nlpUtils/OPLparser.py
> +    @out: objectList, sentences, list of sentenced contained in the OPL file
fixed

2023-06-13 15:43 UTC, mandd commented on src/utils/nlpUtils/OPLparser.py
> +    @out: objectList: sentences, list of sentenced contained in the OPL file
fixed

2023-06-13 20:13 UTC, wangcj05 approved these changes
PR looks good.

2023-06-14 14:45 UTC, wangcj05 commented
PR looks good.

2023-06-14 14:45 UTC, merged